services:
  videodown:
    build: .
    container_name: videodown_web
    restart: unless-stopped
    ports:
      - "5080:5000"
    volumes:
      - .:/app
      - ./downloads:/app/downloads
    environment:
      - PYTHONUNBUFFERED=1
    dns:
      - 8.8.8.8
      - 1.1.1.1
